2023-08-04 10:23:17,826 ERROR: Exception on /user [GET] [in C:\Users\fabbr\Desktop\iberu\backend\env\Lib\site-packages\flask\app.py:1414]
Traceback (most recent call last):
  File "C:\Users\fabbr\Desktop\iberu\backend\env\Lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\fabbr\Desktop\iberu\backend\env\Lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\fabbr\Desktop\iberu\backend\env\Lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\fabbr\Desktop\iberu\backend\env\Lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\fabbr\Desktop\iberu\backend\env\Lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\fabbr\Desktop\iberu\backend\app\main\routes.py", line 217, in user
    return render_template('user.html', context=context, profile_form=profile_form, password_form=password_form)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\fabbr\Desktop\iberu\backend\env\Lib\site-packages\flask\templating.py", line 151, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\fabbr\Desktop\iberu\backend\env\Lib\site-packages\flask\templating.py", line 132, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\fabbr\Desktop\iberu\backend\env\Lib\site-packages\jinja2\environment.py", line 1301, in render
    self.environment.handle_exception()
  File "C:\Users\fabbr\Desktop\iberu\backend\env\Lib\site-packages\jinja2\environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\fabbr\Desktop\iberu\backend\app\templates\user.html", line 455, in top-level template code
    <form id="user-password-form" action="{{ url_for('api.reset_password_request') }}" method="post">
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\fabbr\Desktop\iberu\backend\env\Lib\site-packages\flask\app.py", line 1697, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\fabbr\Desktop\iberu\backend\env\Lib\site-packages\flask\app.py", line 1686, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\fabbr\Desktop\iberu\backend\env\Lib\site-packages\werkzeug\routing\map.py", line 950, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'api.reset_password_request'. Did you mean 'auth.reset_password_request' instead?
2023-08-04 10:24:02,940 INFO: Iberu-TS startup [in C:\Users\fabbr\Desktop\iberu\backend\app\__init__.py:80]
2023-08-04 10:24:03,992 ERROR: Exception on /user [GET] [in C:\Users\fabbr\Desktop\iberu\backend\env\Lib\site-packages\flask\app.py:1414]
Traceback (most recent call last):
  File "C:\Users\fabbr\Desktop\iberu\backend\env\Lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\fabbr\Desktop\iberu\backend\env\Lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\fabbr\Desktop\iberu\backend\env\Lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\fabbr\Desktop\iberu\backend\env\Lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\fabbr\Desktop\iberu\backend\env\Lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\fabbr\Desktop\iberu\backend\app\main\routes.py", line 217, in user
    return render_template('user.html', context=context, profile_form=profile_form, password_form=password_form)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\fabbr\Desktop\iberu\backend\env\Lib\site-packages\flask\templating.py", line 151, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\fabbr\Desktop\iberu\backend\env\Lib\site-packages\flask\templating.py", line 132, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\fabbr\Desktop\iberu\backend\env\Lib\site-packages\jinja2\environment.py", line 1301, in render
    self.environment.handle_exception()
  File "C:\Users\fabbr\Desktop\iberu\backend\env\Lib\site-packages\jinja2\environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\fabbr\Desktop\iberu\backend\app\templates\user.html", line 455, in top-level template code
    <form id="user-password-form" action="{{ url_for('api.reset_password_request') }}" method="post">
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\fabbr\Desktop\iberu\backend\env\Lib\site-packages\flask\app.py", line 1697, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\fabbr\Desktop\iberu\backend\env\Lib\site-packages\flask\app.py", line 1686, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\fabbr\Desktop\iberu\backend\env\Lib\site-packages\werkzeug\routing\map.py", line 950, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'api.reset_password_request'. Did you mean 'auth.reset_password_request' instead?
2023-08-04 10:24:07,433 ERROR: Exception on /user [GET] [in C:\Users\fabbr\Desktop\iberu\backend\env\Lib\site-packages\flask\app.py:1414]
Traceback (most recent call last):
  File "C:\Users\fabbr\Desktop\iberu\backend\env\Lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\fabbr\Desktop\iberu\backend\env\Lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\fabbr\Desktop\iberu\backend\env\Lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\fabbr\Desktop\iberu\backend\env\Lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\fabbr\Desktop\iberu\backend\env\Lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\fabbr\Desktop\iberu\backend\app\main\routes.py", line 217, in user
    return render_template('user.html', context=context, profile_form=profile_form, password_form=password_form)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\fabbr\Desktop\iberu\backend\env\Lib\site-packages\flask\templating.py", line 151, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\fabbr\Desktop\iberu\backend\env\Lib\site-packages\flask\templating.py", line 132, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\fabbr\Desktop\iberu\backend\env\Lib\site-packages\jinja2\environment.py", line 1301, in render
    self.environment.handle_exception()
  File "C:\Users\fabbr\Desktop\iberu\backend\env\Lib\site-packages\jinja2\environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\fabbr\Desktop\iberu\backend\app\templates\user.html", line 455, in top-level template code
    <form id="user-password-form" action="{{ url_for('api.reset_password_request') }}" method="post">
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\fabbr\Desktop\iberu\backend\env\Lib\site-packages\flask\app.py", line 1697, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\fabbr\Desktop\iberu\backend\env\Lib\site-packages\flask\app.py", line 1686, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\fabbr\Desktop\iberu\backend\env\Lib\site-packages\werkzeug\routing\map.py", line 950, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'api.reset_password_request'. Did you mean 'auth.reset_password_request' instead?
2023-08-04 10:24:51,070 INFO: Iberu-TS startup [in C:\Users\fabbr\Desktop\iberu\backend\app\__init__.py:80]
